name: Addon-Check

on:
  push:
    branches:
      - leia
    tags-ignore:
      - v**
  pull_request:
    branches:
      - leia
jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: leia

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.1
      with:
        kodi-version: leia
        addon-id: ${{ github.event.repository.name }}

  check-black:
    needs: kodi-addon-checker
    runs-on: ubuntu-latest
    name: Check Black Style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
