name: Addon-Check

on:
  push:
    branches:
      - matrix
      tags-ignore:
        - v**

  pull_request:
    branches:
      - matrix
jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean workspace
      run: |
        rm -r tools

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.0
      with:
        kodi-version: matrix


  check-black:
    needs: kodi-addon-checker
    runs-on: ubuntu-latest
    name: Check Black Style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
